#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xfce4-pulseaudio-plugin
Version  : 0.4.1
Release  : 1
URL      : https://archive.xfce.org/src/panel-plugins/xfce4-pulseaudio-plugin/0.4/xfce4-pulseaudio-plugin-0.4.1.tar.bz2
Source0  : https://archive.xfce.org/src/panel-plugins/xfce4-pulseaudio-plugin/0.4/xfce4-pulseaudio-plugin-0.4.1.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: xfce4-pulseaudio-plugin-data = %{version}-%{release}
Requires: xfce4-pulseaudio-plugin-lib = %{version}-%{release}
Requires: xfce4-pulseaudio-plugin-locales = %{version}-%{release}
BuildRequires : dbus-glib-dev
BuildRequires : dbus-glib-lib
BuildRequires : intltool
BuildRequires : pkgconfig(exo-1)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libpulse-mainloop-glib)
BuildRequires : pkgconfig(libxfce4panel-2.0)
BuildRequires : pkgconfig(libxfce4ui-2)
BuildRequires : pkgconfig(libxfce4util-1.0)
BuildRequires : pkgconfig(libxfconf-0)

%description
Xfce PulseAudio Panel Plugin
============================
The Xfce PulseAudio Plugin is a plugin for the Xfce panel which provides a
convenient way to adjust the audio volume of the [PulseAudio sound system][1]
and to an auto mixer tool like pavucontrol. It can optionally handle
multimedia keys for controlling the audio volume.

%package data
Summary: data components for the xfce4-pulseaudio-plugin package.
Group: Data

%description data
data components for the xfce4-pulseaudio-plugin package.


%package lib
Summary: lib components for the xfce4-pulseaudio-plugin package.
Group: Libraries
Requires: xfce4-pulseaudio-plugin-data = %{version}-%{release}

%description lib
lib components for the xfce4-pulseaudio-plugin package.


%package locales
Summary: locales components for the xfce4-pulseaudio-plugin package.
Group: Default

%description locales
locales components for the xfce4-pulseaudio-plugin package.


%prep
%setup -q -n xfce4-pulseaudio-plugin-0.4.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1558293452
export GCC_IGNORE_WERROR=1
export LDFLAGS="${LDFLAGS} -fno-lto"
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1558293452
rm -rf %{buildroot}
%make_install
%find_lang xfce4-pulseaudio-plugin

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/icons/hicolor/48x48/apps/xfce4-pulseaudio-plugin.png
/usr/share/icons/hicolor/scalable/apps/xfce4-pulseaudio-plugin.svg
/usr/share/icons/hicolor/scalable/status/audio-volume-high-symbolic.svg
/usr/share/icons/hicolor/scalable/status/audio-volume-low-symbolic.svg
/usr/share/icons/hicolor/scalable/status/audio-volume-medium-symbolic.svg
/usr/share/icons/hicolor/scalable/status/audio-volume-muted-symbolic.svg
/usr/share/icons/hicolor/scalable/status/microphone-sensitivity-high-symbolic.svg
/usr/share/icons/hicolor/scalable/status/microphone-sensitivity-low-symbolic.svg
/usr/share/icons/hicolor/scalable/status/microphone-sensitivity-medium-symbolic.svg
/usr/share/icons/hicolor/scalable/status/microphone-sensitivity-muted-symbolic.svg
/usr/share/xfce4/panel/plugins/pulseaudio.desktop

%files lib
%defattr(-,root,root,-)
/usr/lib64/xfce4/panel/plugins/libpulseaudio-plugin.so

%files locales -f xfce4-pulseaudio-plugin.lang
%defattr(-,root,root,-)

